schema_version = "1.0.0"
id = "export_nurbs_3dm"
version = "0.7.0"
name = "Export NURBS 3DM"
tagline = "Export NURBS surfaces to Rhino 3DM format using rhino3dm"
maintainer = "Keith Sloan"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Write 3DM files to disk"
